language: perl
matrix:
  include:
  - perl: "5.30"
    dist: bionic
  - perl: "5.28"
    dist: bionic
  - perl: "5.26"
    dist: bionic
  - perl: "5.24"
    dist: bionic
  - perl: "5.22"
    dist: bionic
  - perl: "5.20"
    dist: bionic
  - perl: "5.30"
    dist: xenial
  - perl: "5.28"
    dist: xenial
  - perl: "5.26"
    dist: xenial
  - perl: "5.24"
    dist: xenial
  - perl: "5.22"
    dist: xenial
  - perl: "5.20"
    dist: trusty
  - perl: "5.18"
    dist: trusty
  - perl: "5.16"
    dist: trusty
  - perl: "5.14"
    dist: trusty
  - perl: "5.12"
    dist: trusty
  - perl: "5.10"
    dist: trusty
env:
  global:
    - HARNESS_OPTIONS=j9
    - TEST_EV=1
    - TEST_POD=1
    - TEST_SOCKS=1
    - TEST_SUBPROCESS=1
    - TEST_UNIX=1
    - TEST_TLS=1
install:
  - cpanm -n Cpanel::JSON::XS EV~"!= 4.28" IO::Socket::Socks IO::Socket::SSL
  - cpanm -n Net::DNS::Native Role::Tiny Test::Pod Test::Pod::Coverage
  - cpanm -n --installdeps .
sudo: false
notifications:
  email: false
