language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "dev"
  - "blead"
matrix:
  allow_failures:
    - perl: "dev"
    - perl: "blead"
  fast_finish: true
env:
  - HARNESS_OPTIONS=j9 TEST_EV=1 TEST_POD=1 TEST_SOCKS=1 TEST_TLS=1
before_install:
  - git clone git://github.com/haarg/perl-travis-helper
  - source perl-travis-helper/init
  - build-perl
  - perl -V
install:
  - cpanm -n EV IO::Socket::Socks IO::Socket::SSL Net::DNS::Native Test::Pod Test::Pod::Coverage
  - cpanm -n --installdeps .
sudo: false
notifications:
  email: false
